version: '3.8'
services:
    postgres:
        image: postgres:latest
        environment:
          - POSTGRES_USER=dbuser
          - POSTGRES_PASSWORD=admin1234
          - POSTGRES_DB=benchmark
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    
    mongodb_container:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./mongodb-data:/data/db